# Site settings
title: Kim Dong Hyun
description: 'Unity 3D/2D 게임 개발자 김동현 포트폴리오' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmmdong.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "on"

highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Kim Dong Hyun # add your name
author-pic: profile.png
about-author: Unity 기반 캐주얼 RPG 를 다수 런칭하고 라이브 서비스를 운영해 온 게임 클라이언트 개발자.

# Contact links
email: clxlzl1234@gmail.com # Add your Email address
website: https://mmmdong.github.io # Add your website
github: mmmdong # Add your Github handle
phone: "010-6299-6530"
notion: https://www.notion.so/mmmdong/Unity-Programmer-Kim-Dong-Hyun-33c08b60233e805f929ad17f7caf3207

# Newsletter

# Tracker

# Paginate
words_per_minute: 200

# Comments
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
encoding: "utf-8"
highlighter: rouge

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "Dockerfile", "docker-compose.yaml", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "_config_docker.yml", "vendor/"]